### ISSUE TITLE
add new places - frontend

### ISSUE THREAD

**Issue by targence** [lab0x0/szmakermap#18]
feedback about add a new place

- coordinates should be also fields in form
- when open not need set default coordinates
- when click on map, coordinates fields data should be updated.
- also don't like idea with 2 column when english on the left and chinese on the right, will be better to have only one column in form

some little thing like order I will fix myself... it's not so important in this stage.

**Comment by clemsos** [comment]
closed by 195ffc10ef9afc1150f2a90da96930957a06d2af
