### ISSUE TITLE
Hours not present

### ISSUE THREAD

**Issue by globalcitizen** [lab0x0/szmakermap#8]
Many of these places have limited opening hours, eg. weekends only, after hours only, business hours only, etc. It would be good to include some basic info on this if possible to prevent people from wasting their time crossing town.

**Comment by clemsos** [comment]
Is that solved ? I have seen that a property was added to the data model, but what is the format? Hours are always painful to store. Some are open only in the weekends, some every day, etc. Do we have a model for that ?

**Comment by clemsos** [comment]
JSON specifications from schema.org looks overkill but provides some direction http://schema.org/OpeningHoursSpecification

**Comment by clemsos** [comment]
Something like could work but then hours could also be different for each day of the week
 
{
   "opens": "09:00",
   "closes": "11:00",
   "days of the week" : [ ... ]
}

**Comment by clemsos** [comment]
2nd option 

```
{
'Mo' : {
  "opens": "09:00",
  "closes" : "11:00"
},
'Tue' : {
  "opens": "09:00",
  "closes" : "11:00"
},
...
'Sun' : {
  "opens": "09:00",
  "closes" : "11:00"
},
```

**Comment by globalcitizen** [comment]
From past experience I would suggest simply using a localized string unless you absolutely need real time access to machine calculable hours.

**Comment by clemsos** [comment]
works fine with me. What will that look like ?
